version: "3.9"
services:
  artemis:
    build: "./Artemis"
    container_name: "artemis"
    # Persistent volume
    # Make sure you prune to get clean state for test runs
    volumes:
      - artemis-data:/var/lib/artemis/data
    ports:
      - "8161:8161"
    # You can set up limits here
    # But make sure you also correct java memory in artemis Dockerfile in order to have effect.
    deploy:
      resources:
        reservations:
          memory: 8g

  producer-bbc.com:
    # This is the producer service, you can have multiple of them
    build: ./Aggregator
    command: [ "--to=2021-03-20", "--since=2021-01-20", "bbc.com" ]
    depends_on:
      - consumer

  # This is consumer spawn as many as you want, you ideally want to have pills set up to number of producers.
  # Make sure you use use-hostname-output to have disitnguished output folders for each consumer.
  consumer:
    build: ./Processor
    command:
      [
        "--use_hostname_output",
        "--timeout=1",
        "--pills_to_die=1",
        "--queue_size=200"
      ]
    volumes:
      - ./output:/output:z
    deploy:
      # Number of replicas
      replicas: 4
    depends_on:
      - artemis

volumes:
  artemis-data:
