name: Pypi Publish

on:
  release:
    types:
      - created

env:
  PYTHON_VERSION: "3.10"
  TWINE_USERNAME: __token__


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          pip install build twine
      - name: Build and publish package
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m build .
          twine upload dist/*
